name:                image-triangles
version:             0.1.0.0
github:              "jackoe/image-triangles"
license:             BSD3
author:              "Jack Wines"
maintainer:          "jack@winesj.com"
copyright:           "2018 Jack Wines"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jackoe/image-triangles#readme>

dependencies:
- base >= 4.7 && < 5
- hip
- diagrams

library:
  source-dirs: src

executables:
  image-triangles-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - image-triangles

tests:
  image-triangles-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - image-triangles
